### PR TITLE
fix: namespace parsing in gitlab

### PR DESCRIPTION
**Pull request by shyim**
**Thank you for submitting this pull request**

URLs like `https://gitlab.shopware.com/shopware/6/product/commercial/-/merge_requests/1645`
cannot be parsed right now as the extractor expects only one path in "namespace". But we have in our org nested stuff

### Checklist
- [ ] Tests added if applicable.
- [ ] Documentation updated if applicable.

> **Note:** `dist/cli/index.js` and `dist/gha/index.js` are automatically generated by git hooks and gh workflows.

<details>
<summary>
First time here?
</summary>

This project follows [git conventional commits](https://gist.github.com/qoomon/5dfcdf8eec66a051ecd85625518cfd13) pattern, therefore the commits should have the following format:

```
<type>(<optional scope>): <subject>
empty separator line
<optional body>
empty separator line
<optional footer>
```

Where the type must be one of `[build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test]`

> **NOTE**: if you are still in a `work in progress` branch and you want to push your changes remotely, consider adding `--no-verify` for both `commit` and `push`, e.g., `git push origin <feat-branch> --no-verify` - this could become useful to push changes where there are still tests failures. Once the pull request is ready, please `amend` the commit and force-push it to keep following the adopted git commit standard. 

</details>

<details>
<summary>
How to prepare for a new release?
</summary>

There is no need to manually update `package.json` version and `CHANGELOG.md` information. This process has been automated in [Prepare Release](./workflows/prepare-release.yml) *Github* workflow.

Therefore whenever enough changes are merged into the `main` branch, one of the maintainers will trigger this workflow that will automatically update `version` and `changelog` based on the commits on the git tree.

More details can be found in [package release](https://github.com/kiegroup/git-backporting/blob/main/README.md#package-release) section of the README.
</details>

### CODE REVIEW

**Comment by lampajr** [comment]
Hey @shyim , the change looks great to me.
I just added a simple test to ensure the result is the expected one, do you mind to double check it: a3814cb44eda8b492eb2e69fbb146ece289c8391 ?

After that, unfortunately I do not have any real nested scenario to test against, so if you have your concrete example I would appreciate if you can run the cmd line tool against your own nested repo to check if that works as expected - you can just `npm run compile` and then call the cmd line tool (maybe you already did that :) ).

**Comment by shyim** [comment]
Hey,

I have tested it works great. 👍

**Review by lampajr — APPROVED** [review]
lgtm! Thanks again @shyim for your contribution :heart:

**Comment by shyim** [comment]
Could you maybe tag a new version? I would like to integrate it in our pipeline ❤️

**Comment by lampajr** [comment]
> Could you maybe tag a new version? I would like to integrate it in our pipeline ❤️

Here it is https://github.com/kiegroup/git-backporting/releases/tag/v4.4.1 and https://www.npmjs.com/package/@kie/git-backporting/v/4.4.1

**Pull request merged**
